package tui

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"forge/internal/initmd"
)

// handleInitCommand is the /init slash command. It populates AGENTS.md
// from the project snapshot. AGENTS.md sits at tier-A in the prompt
// cache (internal/context/builder.go), so we go to some lengths to
// avoid clobbering user-authored content:
//
//   - /init               — generates AGENTS.md only when the file is
//                           absent or matches a previous /init output.
//                           User-authored bytes are left alone and the
//                           command returns a hint.
//   - /init refresh       — backs the existing file up to AGENTS.md.bak
//                           (overwriting any prior backup) and rewrites
//                           AGENTS.md unconditionally.
//   - /init show          — renders the would-be AGENTS.md to the
//                           viewport without touching disk.
//
// "Forge-generated" detection is substring-based on the trailing HTML
// comment that initmd.Build appends. Users wanting to take ownership
// can simply delete that line.
func (m *model) handleInitCommand(fields []string) string {
	t := m.theme
	if m.options.ProjectState == nil {
		return t.ErrorStyle.Render("Project state service unavailable (forge.db failed to open).")
	}

	sub := ""
	if len(fields) >= 2 {
		sub = fields[1]
	}

	switch sub {
	case "show":
		return m.renderInitPreview()
	case "refresh":
		return m.runInit(true)
	case "":
		return m.runInit(false)
	default:
		return "Usage: /init [show|refresh]"
	}
}

func (m *model) renderInitPreview() string {
	t := m.theme
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	rendered, err := initmd.Build(ctx, m.options.CWD, m.options.ProjectState, initmd.BuildOptions{})
	if err != nil {
		return t.ErrorStyle.Render("init: " + err.Error())
	}
	header := t.Muted.Render("preview — /init refresh to write to AGENTS.md\n\n")
	return header + rendered
}

func (m *model) runInit(force bool) string {
	t := m.theme
	path := filepath.Join(m.options.CWD, "AGENTS.md")
	existing, statErr := os.ReadFile(path)
	exists := statErr == nil

	if exists && !force && !initmd.IsForgeGenerated(string(existing)) {
		return t.Warning.Render("AGENTS.md already exists and was not generated by /init.\n"+
			"Run `/init refresh` to overwrite (a backup will be saved to AGENTS.md.bak), "+
			"or `/init show` to preview without touching the file.") + "\n"
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	rendered, err := initmd.Build(ctx, m.options.CWD, m.options.ProjectState, initmd.BuildOptions{})
	if err != nil {
		return t.ErrorStyle.Render("init: " + err.Error())
	}

	backupNote := ""
	if exists {
		backupPath := path + ".bak"
		if err := os.Rename(path, backupPath); err != nil {
			return t.ErrorStyle.Render(fmt.Sprintf("init: backup failed: %s", err))
		}
		backupNote = "\n" + t.Muted.Render("backup saved to AGENTS.md.bak")
	}

	if err := os.WriteFile(path, []byte(rendered), 0o644); err != nil {
		return t.ErrorStyle.Render("init: write failed: " + err.Error())
	}

	verb := "wrote"
	if exists {
		verb = "refreshed"
	}
	return t.Success.Render(fmt.Sprintf("%s AGENTS.md (%d bytes)", verb, len(rendered))) + backupNote
}
