package tools

func RegisterBuiltins(registry *Registry) {
	registry.Register(readFileTool{}, "Read")
	registry.Register(listFilesTool{}, "LS")
	registry.Register(searchTextTool{}, "Grep")
	registry.Register(searchFilesTool{}, "Glob")
	registry.Register(gitStatusTool{})
	registry.Register(gitDiffTool{})
	registry.Register(editFileTool{}, "Edit")
	registry.Register(writeFileTool{}, "Write")
	registry.Register(applyPatchTool{})
	registry.Register(runCommandTool{}, "Bash", "PowerShell")
	registry.Register(todoWriteTool{}, "TodoWrite")
	registry.Register(noopTool{name: "spawn_subagent", description: "Spawn a limited subagent worker."}, "Agent", "Task")
	registry.Register(noopTool{name: "task_create", description: "Create a visible task in the session plan."}, "TaskCreate")
	registry.Register(noopTool{name: "task_list", description: "List visible session plan tasks."}, "TaskList")
	registry.Register(noopTool{name: "task_get", description: "Get a visible session plan task."}, "TaskGet")
	registry.Register(noopTool{name: "task_update", description: "Update a visible session plan task."}, "TaskUpdate")
	registry.Register(askUserTool{}, "AskUserQuestion")
	registry.Register(powershellTool{})
	registry.Register(runSkillTool{}, "Skill")
	registry.Register(webFetchTool{}, "WebFetch")
	registry.Register(webSearchTool{}, "WebSearch")
	registry.Register(noopTool{name: "list_mcp_resources", description: "Compatibility stub for listing MCP resources; implementation pending."}, "ListMcpResourcesTool")
	registry.Register(noopTool{name: "read_mcp_resource", description: "Compatibility stub for reading MCP resources; implementation pending."}, "ReadMcpResourceTool")
	registry.Register(noopTool{name: "lsp", description: "Compatibility stub for LSP diagnostics/symbols; implementation pending."}, "LSP")
	registry.Register(noopTool{name: "monitor", description: "Compatibility stub for monitoring long-lived commands; implementation pending."}, "Monitor")
}
