package tools

func RegisterBuiltins(registry *Registry) {
	registry.Register(readFileTool{}, "Read")
	registry.Register(listFilesTool{}, "LS")
	registry.Register(searchTextTool{}, "Grep")
	registry.Register(searchFilesTool{}, "Glob")
	registry.Register(gitStatusTool{})
	registry.Register(gitDiffTool{})
	registry.Register(editFileTool{}, "Edit")
	registry.Register(writeFileTool{}, "Write")
	registry.Register(applyPatchTool{})
	registry.Register(runCommandTool{}, "Bash", "PowerShell")
	registry.Register(pythonSetupTool{}, "PythonSetup")
	registry.Register(pythonRunTool{}, "PythonRun")
	registry.Register(planWriteTool{}, "PlanWrite")
	registry.Register(planGetTool{}, "PlanGet")
	registry.Register(todoWriteTool{}, "TodoWrite")
	registry.Register(spawnSubagentTool{}, "Agent", "Task")
	registry.Register(spawnSubagentsTool{}, "Agents", "Tasks")
	registry.Register(taskCreateTool{}, "TaskCreate")
	registry.Register(taskListTool{}, "TaskList")
	registry.Register(taskGetTool{}, "TaskGet")
	registry.Register(taskUpdateTool{}, "TaskUpdate")
	registry.Register(executeTaskTool{}, "ExecuteTask")
	registry.Register(askUserTool{}, "AskUserQuestion")
	registry.Register(powershellTool{})
	registry.Register(runSkillTool{}, "Skill")
	registry.Register(webFetchTool{}, "WebFetch")
	registry.Register(webSearchTool{}, "WebSearch")
	registry.Register(noopTool{name: "list_mcp_resources", description: "Compatibility stub for listing MCP resources; implementation pending."}, "ListMcpResourcesTool")
	registry.Register(noopTool{name: "read_mcp_resource", description: "Compatibility stub for reading MCP resources; implementation pending."}, "ReadMcpResourceTool")
	registry.Register(noopTool{name: "lsp", description: "Compatibility stub for LSP diagnostics/symbols; implementation pending."}, "LSP")
	registry.Register(noopTool{name: "monitor", description: "Compatibility stub for monitoring long-lived commands; implementation pending."}, "Monitor")
}
