// Package pet renders an animated braille-art robot for embedding inside
// other bubbletea views. It exposes a pure state machine — no Program, no
// global ticker — so a host model can advance the animation on its own
// schedule and place the rendered string anywhere in its layout.
//
// The original standalone demo lives in docs/pet/. The base sprite
// (robot_data.go) is auto-generated from a PNG; see docs/pet/convert.py.
//
// Usage:
//
//	state := pet.New()
//	// each tick (~80ms is comfortable):
//	state = pet.Tick(state)
//	// then render:
//	frame := pet.Render(state)
package pet

import (
	"fmt"
	"math/rand"
	"strings"
	"time"

	"github.com/charmbracelet/lipgloss"
)

// TickInterval is the recommended time between Tick calls. Hosts can pick
// their own cadence; everything below 30ms wastes CPU and above ~150ms
// makes the blink/glow visibly choppy.
const TickInterval = 80 * time.Millisecond

// Cols / Rows are the rendered dimensions of the full sprite, in cells.
// Animations land within these bounds so callers can size their layout.
const (
	Cols = RobotCols
	Rows = RobotRows
)

// SmallCols / SmallRows are kept as aliases of Cols / Rows for
// backwards-compatibility with callers that referenced them when the
// pet was downscaled at runtime. The sprite is now generated natively
// at the desired sidebar-friendly size (18x6) by docs/pet/convert.py,
// so RenderSmall is just an alias of Render.
const (
	SmallCols = Cols
	SmallRows = Rows
)

// region addresses a rectangular block of cells in the base sprite. The
// animation overwrites these blocks on each frame.
type region struct {
	rowMin, rowMax, colMin, colMax int
}

// Regions calibrated for the 18x6 sprite generated by:
//
//	python docs/pet/convert.py --cols 18 --rows 6 --package pet \
//	    --out internal/tui/pet/robot_data.go --debug
//
// The values were tweaked from convert.py's debug suggestions to match
// where the visual elements actually landed after PIL's LANCZOS
// resample (the linear scale doesn't always agree with the rendered
// sprite — empty rows at top/bottom of the original shifted things).
//
// At 18x6 each "eye" is a single (col-wide pair, row-tall) cell, and
// the mouth is a 5-cell-wide bar in the lower face. If you regen the
// sprite at a different size, re-inspect the new robot_data.go and
// update these constants by eye.
var (
	leftEye   = region{2, 2, 6, 7}
	rightEye  = region{2, 2, 9, 10}
	mouth     = region{3, 3, 6, 10}
	sparkZone = region{0, 0, 4, 12}
)

// Eye animation frames sized for the 18x6 sprite. Each frame is a
// single row × 2 columns — that's the entire "eye" cell pair in the
// regenerated visor (e.g. `⣾⣷` at default). A space is "transparent":
// it lets the underlying base sprite show through, so omitting frames
// (eyeOpen below) means "no overlay, keep the visor as-is".

var eyeOpen = []string{
	"  ", // transparent — show the base visor
}

var eyeBlink = []string{
	"⠒⠒", // closed eye / mid line
}

var eyeHappy = []string{
	"⠉⠉", // arched closed eye / smile
}

type sparkle struct {
	row, col int
	life     int
	char     string
}

// State is the snapshot of the pet's animation. It's intentionally
// value-typed and copyable — Tick returns a new State so callers can keep
// it alongside their bubbletea model fields without worrying about
// shared mutability across goroutines.
type State struct {
	Tick      int
	Blinking  bool
	BlinkLeft int
	MouthGlow float64
	Sparkles  []sparkle
	rng       *rand.Rand
}

// New returns an initial State seeded from the current time so each
// program-launch shows a slightly different animation pattern.
func New() State {
	return State{
		rng: rand.New(rand.NewSource(time.Now().UnixNano())),
	}
}

// Tick advances the animation by one frame. Call this on the host's
// timer (TickInterval is the recommended cadence). Returns a fresh State
// so the host can store it back into its model field.
func Tick(s State) State {
	if s.rng == nil {
		s.rng = rand.New(rand.NewSource(time.Now().UnixNano()))
	}
	s.Tick++

	if s.BlinkLeft > 0 {
		s.BlinkLeft--
		if s.BlinkLeft == 0 {
			s.Blinking = false
		}
	} else if s.rng.Intn(40) == 0 {
		s.Blinking = true
		s.BlinkLeft = 2
	}

	phase := float64(s.Tick%50) / 50.0
	if phase < 0.5 {
		s.MouthGlow = phase * 2
	} else {
		s.MouthGlow = (1 - phase) * 2
	}

	alive := s.Sparkles[:0]
	for _, sp := range s.Sparkles {
		sp.life--
		if sp.life > 0 {
			alive = append(alive, sp)
		}
	}
	s.Sparkles = alive
	if s.rng.Intn(2) == 0 && len(s.Sparkles) < 8 {
		chars := []string{"·", "✦", "✧", "⋆", "*"}
		s.Sparkles = append(s.Sparkles, sparkle{
			row:  sparkZone.rowMin + s.rng.Intn(sparkZone.rowMax-sparkZone.rowMin+1),
			col:  sparkZone.colMin + s.rng.Intn(sparkZone.colMax-sparkZone.colMin+1),
			life: 4 + s.rng.Intn(6),
			char: chars[s.rng.Intn(len(chars))],
		})
	}
	return s
}

// Render produces the full lipgloss-styled sprite. Truecolor terminal
// recommended (Windows Terminal, WezTerm, Alacritty, Kitty, iTerm2).
// Returns Cols-wide lines joined with \n; the host is responsible for
// placing it inside its own layout.
func Render(s State) string {
	chars, colors := composeFrame(s)
	return emitGrid(chars, colors, 0, RobotRows, 0, RobotCols)
}

// RenderSmall is preserved as an alias of Render for backwards
// compatibility with hosts that referenced the runtime-downscaled API.
// Now that the sprite is generated natively at the desired sidebar size
// (see docs/pet/convert.py --cols 18 --rows 6), there's no scaling left
// to do — the function just returns Render(s).
func RenderSmall(s State) string {
	return Render(s)
}

// composeFrame builds the full chars/colors grid for the current State,
// applying eye, mouth, and sparkle overlays on top of the base sprite.
// Both Render and RenderCompact share this so the animation logic stays
// in one place.
func composeFrame(s State) ([][]string, [][][3]uint8) {
	chars := make([][]string, RobotRows)
	colors := make([][][3]uint8, RobotRows)
	for r := 0; r < RobotRows; r++ {
		chars[r] = make([]string, RobotCols)
		colors[r] = make([][3]uint8, RobotCols)
		copy(chars[r], RobotChars[r])
		copy(colors[r], RobotColors[r])
	}

	eyeFrame := eyeOpen
	currentEyeColor := [3]uint8{0xFF, 0xB3, 0x47}
	if s.Blinking {
		eyeFrame = eyeBlink
		currentEyeColor = [3]uint8{0xFF, 0x8C, 0x42}
	} else if s.Tick%200 < 30 {
		eyeFrame = eyeHappy
	}
	paintRegion(chars, colors, leftEye, eyeFrame, currentEyeColor)
	paintRegion(chars, colors, rightEye, eyeFrame, currentEyeColor)

	cyanDim := [3]uint8{0x10, 0x60, 0x70}
	cyanBright := [3]uint8{0x40, 0xE0, 0xFF}
	mouthColor := lerpColor(cyanDim, cyanBright, s.MouthGlow)
	for r := mouth.rowMin; r <= mouth.rowMax; r++ {
		for c := mouth.colMin; c <= mouth.colMax; c++ {
			if r >= 0 && r < RobotRows && c >= 0 && c < RobotCols {
				if chars[r][c] != " " {
					colors[r][c] = mouthColor
				}
			}
		}
	}

	for _, sp := range s.Sparkles {
		if sp.row >= 0 && sp.row < RobotRows && sp.col >= 0 && sp.col < RobotCols {
			t := float64(sp.life) / 8.0
			if t > 1 {
				t = 1
			}
			c := lerpColor([3]uint8{0x40, 0x20, 0x00}, [3]uint8{0xFF, 0xA0, 0x40}, t)
			chars[sp.row][sp.col] = sp.char
			colors[sp.row][sp.col] = c
		}
	}
	return chars, colors
}

// emitGrid renders the [rowStart, rowEnd) x [colStart, colEnd) sub-grid
// of the composed frame into a styled string. Bounds outside the actual
// grid are clamped so callers can pass the constant crop windows
// without bounds-check boilerplate.
func emitGrid(chars [][]string, colors [][][3]uint8, rowStart, rowEnd, colStart, colEnd int) string {
	if rowStart < 0 {
		rowStart = 0
	}
	if rowEnd > RobotRows {
		rowEnd = RobotRows
	}
	if colStart < 0 {
		colStart = 0
	}
	if colEnd > RobotCols {
		colEnd = RobotCols
	}
	var sb strings.Builder
	for r := rowStart; r < rowEnd; r++ {
		for c := colStart; c < colEnd; c++ {
			ch := chars[r][c]
			if ch == " " {
				sb.WriteString(" ")
				continue
			}
			col := colors[r][c]
			style := lipgloss.NewStyle().Foreground(lipgloss.Color(rgbHex(col)))
			sb.WriteString(style.Render(ch))
		}
		if r < rowEnd-1 {
			sb.WriteString("\n")
		}
	}
	return sb.String()
}

func paintRegion(grid [][]string, colors [][][3]uint8, r region, frame []string, color [3]uint8) {
	for dy, line := range frame {
		row := r.rowMin + dy
		if row < 0 || row >= len(grid) {
			continue
		}
		col := r.colMin
		for _, ch := range line {
			if col >= 0 && col < len(grid[row]) {
				if ch != ' ' {
					grid[row][col] = string(ch)
					colors[row][col] = color
				}
			}
			col++
		}
	}
}

func lerpColor(a, b [3]uint8, t float64) [3]uint8 {
	if t < 0 {
		t = 0
	}
	if t > 1 {
		t = 1
	}
	return [3]uint8{
		uint8(float64(a[0]) + (float64(b[0])-float64(a[0]))*t),
		uint8(float64(a[1]) + (float64(b[1])-float64(a[1]))*t),
		uint8(float64(a[2]) + (float64(b[2])-float64(a[2]))*t),
	}
}

func rgbHex(c [3]uint8) string {
	return fmt.Sprintf("#%02X%02X%02X", c[0], c[1], c[2])
}
